version: '3.8'

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pocketbase-data:/pb_data
    networks:
      - weather-app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: weather-backend
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - COLLECTOR_SERVICE_URL=http://collector:3001
      - POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      - pocketbase
    networks:
      - weather-app-network

  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: weather-collector
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - POCKETBASE_URL=http://pocketbase:8090
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    depends_on:
      - pocketbase
    networks:
      - weather-app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: weather-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      - collector
    networks:
      - weather-app-network

networks:
  weather-app-network:
    driver: bridge

volumes:
  pocketbase-data: 